# Generated by Django 3.1.7 on 2021-04-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210321_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
