# Generated by Django 3.1.7 on 2021-04-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210406_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
