# Generated by Django 3.1.7 on 2021-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210406_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
