# Generated by Django 3.1.7 on 2021-04-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210406_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
