# Generated by Django 3.1.7 on 2021-04-06 21:58
from django.template.defaultfilters import slugify
from django.db import migrations

def populate_slug(apps, schema_editor):
    Person = apps.get_model('main_app', 'Person')

    persons = Person.objects.all()
    for person in persons:
        slug = slugify(person.name)
        person.slug = slug[:50]
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_person_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slug, migrations.RunPython.noop)
    ]
